his/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('home.urls')),
    url(r'^', include('user.urls')),
    url(r'^', include('department.urls')),
    url(r'^', include('patient.urls')),
    url(r'^', include('polyclinic.urls')),
    url(r'^', include('icu.urls')),
    url(r'^', include('laboratory.urls')),
    url(r'^', include('discharge.urls')),
    url(r'^', include('emergency.urls')),
    url(r'^', include('operation.urls')),


]

operation/urls.py
from django.conf.urls import url
from operation import views


urlpatterns = [

    # 手术记录
    url(r'^indexOperation/$', views.indexOperation, name='indexOperation'),

    url(r'^addOperationRecord/(\d+)$', views.addOperationRecord, name='addOperationRecord'),
    url(r'^editOperationRecord/(\d+)/(\d+)$', views.editOperationRecord, name='editOperationRecord'),
    url(r'^deleteOperationRecord/(\d+)/(\d+)$', views.deleteOperationRecord, name='deleteOperationRecord'),

    url(r'^operationDetail/(\d+)$', views.operationDetail, name='operationDetail'),

    url(r'^searchOperationPatient/$', views.searchOperationPatient, name='searchOperationPatient'),
    url(r'^dateSearchOperation/$', views.dateSearchOperation, name='dateSearchOperation'),

    url(r'^allOperationPatient/$', views.allOperationPatient, name='allOperationPatient'),

    # 手术预约
    url(r'^indexBooking/$', views.indexBooking, name='indexBooking'),

    url(r'^newPatientBooking/$', views.newPatientBooking, name='newPatientBooking'),
    url(r'^bookingOperation/(\d+)$', views.bookingOperation, name='bookingOperation'),
    url(r'^editBooking/(\d+)$', views.editBooking, name='editBooking'),
    url(r'^deleteBooking/(\d+)$', views.deleteBooking, name='deleteBooking'),

    url(r'^allBookingPatients/$', views.allBookingPatients, name='allBookingPatients'),

    url(r'^bookingDetail/(\d+)$', views.bookingDetail, name='bookingDetail'),

    url(r'^searchBookingPatient/$', views.searchBookingPatient, name='searchBookingPatient'),
    url(r'^dateSearchBooking/$', views.dateSearchBooking, name='dateSearchBooking'),

    url(r'^bookingList/$', views.bookingList, name='bookingList'),

    url(r'^dateSearchBookingList/$', views.dateSearchBookingList, name='dateSearchBookingList'),

]

operation/models.py
from django.db import models
from patient.models import PatientInfo


class Operation(models.Model):

    patient = models.ForeignKey(PatientInfo, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=35)  # 手术名称
    doctor = models.CharField(max_length=35)  # 医生名称
    assistant = models.CharField(max_length=35)  # 助手
    surgicalNurse = models.CharField(max_length=20)  # 手术护士
    anesthetist = models.CharField(max_length=35)  # 麻醉师名称
    typesNarcosis = models.CharField(max_length=15)  # 麻醉类型
    typesOperation = models.CharField(max_length=10)  # 手术类型
    roomNo = models.CharField(max_length=20)  # 房号
    begin = models.DateTimeField()  # 手术开始时间
    timeOfOperation = models.SmallIntegerField()  # 手术时间
    recordDate = models.DateTimeField(auto_now_add=True)  # 记录时间
    operator = models.CharField(max_length=35, default='')  # 操作员


class TimeTable(models.Model):
    """医生时间表"""

    doctor = models.CharField(max_length=35)  # 医生名称
    date = models.DateField()  # 手术开始时间


class BookingOperation(models.Model):
    """手术预约"""

    timeTable = models.ForeignKey(TimeTable, on_delete=models.DO_NOTHING)
    patient = models.ForeignKey(PatientInfo, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=35)  # 手术名称
    # doctor = models.CharField(max_length=35)  # 医生名称
    date = models.DateField()  # 手术开始时间
    timeOfOperation = models.SmallIntegerField(default=1)  # 手术时间, 1表示一个小时
    operator = models.CharField(max_length=35, default='')  # 操作员
    order = models.SmallIntegerField(default=1)  # 手术预定顺序


class OperationDictionary(models.Model):
    """手术名称表"""

    name = models.CharField(max_length=35)  # 手术名称

operation/views.py
from django.db.models import Q
from django.shortcuts import render, redirect
from user.views import login_required
from user.models import User
from patient.models import PatientInfo, BasicInfo
from department.models import Department
from operation.models import *
from datetime import datetime, date, timedelta
from patient.function import IDCreator


@login_required
def indexOperation(request):

    user = User.objects.all().get(name=request.session['name'])

    # 更新当前模板内容
    user.currentTemplateUrl = 'indexOperation'
    user.save()

    # 病房
    wards = user.authorityWard.filter(status=True)

    return render(request, 'operation/indexOperation.html', locals())


@login_required
def indexBooking(request):

    user = User.objects.all().get(name=request.session['name'])

    # 更新当前模板内容
    user.currentTemplateUrl = 'indexBooking'
    user.save()

    # 科室
    departments = Department.objects.filter(Q(status=True, types=2) | Q(status=True, types=3))

    return render(request, 'operation/indexBooking.html', locals())


@login_required
def addOperationRecord(request, patient_id):
    """添加手术记录"""

    username = request.session['name']

    if request.method == 'POST':
        name = request.POST.get('name')
        doctor = request.POST.get('doctor')
        assistant = request.POST.get('assistant')
        surgicalNurse = request.POST.get('surgicalNurse')
        anesthetist = request.POST.get('anesthetist')
        typesNarcosis = request.POST.get('typesNarcosis')
        typesOperation = request.POST.get('typesOperation')
        roomNo = request.POST.get('roomNo')
        begin = request.POST.get('begin')
        timeOfOperation = request.POST.get('timeOfOperation')

        Operation.objects.create(patient_id=patient_id, name=name, doctor=doctor, assistant=assistant,
                                 surgicalNurse=surgicalNurse, anesthetist=anesthetist,
                                 typesNarcosis=typesNarcosis, roomNo=roomNo, typesOperation=typesOperation,
                                 begin=begin, timeOfOperation=timeOfOperation, operator=username)

        # 更新手术名称表
        if OperationDictionary.objects.filter(name=name):
            pass
        else:
            OperationDictionary.objects.create(name=name)

        return redirect('/operationDetail/' + patient_id)


@login_required
def editOperationRecord(request, patient_id, operation_id):
    """编辑手术记录"""

    username = request.session['name']

    if request.method == 'POST':
        name = request.POST.get('name')
        doctor = request.POST.get('doctor')
        assistant = request.POST.get('assistant')
        surgicalNurse = request.POST.get('surgicalNurse')
        anesthetist = request.POST.get('anesthetist')
        typesNarcosis = request.POST.get('typesNarcosis')
        typesOperation = request.POST.get('typesOperation')
        roomNo = request.POST.get('roomNo')
        begin = request.POST.get('begin')
        timeOfOperation = request.POST.get('timeOfOperation')

        operation = Operation.objects.get(id=operation_id)

        operation.name = name
        operation.doctor = doctor
        operation.assistant = assistant
        operation.surgicalNurse = surgicalNurse
        operation.anesthetist = anesthetist
        operation.typesNarcosis = typesNarcosis
        operation.typesOperation = typesOperation
        operation.roomNo = roomNo
        operation.begin = begin
        operation.timeOfOperation = timeOfOperation
        operation.operator = username
        operation.save()

        return redirect('/operationDetail/' + patient_id)


@login_required
def deleteOperationRecord(request, patient_id, operation_id):
    """删除手术记录"""

    operation = Operation.objects.get(id=operation_id)
    operation.delete()

    return redirect('/operationDetail/' + patient_id)


@login_required
def operationDetail(request, patient_id):
    """手术详情"""

    user = User.objects.get(name=request.session['name'])

    # 病房
    wards = user.authorityWard.filter(status=True)

    patient = PatientInfo.objects.get(id=patient_id)

    operations = Operation.objects.filter(patient_id=patient_id)

    doctors = User.objects.filter(position__name='Doctor')
    nurses = User.objects.filter(position__name='Nurse')

    operationNames = OperationDictionary.objects.all()

    return render(request, 'operation/operationDetail.html', locals())


@login_required
def searchOperationPatient(request):
    """搜索手术病人"""

    user = User.objects.get(name=request.session['name'])

    # 病房
    wards = user.authorityWard.filter(status=True)

    doctors = User.objects.filter(position__name='Doctor')
    nurses = User.objects.filter(position__name='Nurse')

    operationNames = OperationDictionary.objects.all()

    if request.method == 'POST':
        search = request.POST.get('search')

        patients = PatientInfo.objects.filter(Q(basicInfo__name__contains=search) | Q(patientID=search))

        if patients:

            return render(request, 'operation/searchOperationPatient.html', locals())

        else:

            message = 'Not Fond !'

            return render(request, 'operation/searchOperationPatient.html', locals())


@login_required
def operationRecode(request, patient_id, patientID):
    """手术记录"""

    user = User.objects.get(name=request.session['name'])

    # 病房
    wards = user.authorityWard.filter(status=True)

    patient = PatientInfo.objects.get(id=patient_id)

    operations = Operation.objects.filter(patient_id=patient_id)

    return render(request, 'operation/operationRecord.html', locals())


@login_required
def allOperationPatient(request):
    """所有手术病人"""

    user = User.objects.get(name=request.session['name'])

    today = date.today()
    tomorrow = date.today() + timedelta(days=1)
    dates = (today, tomorrow)

    # 病房
    wards = user.authorityWard.filter(status=True)

    doctors = User.objects.filter(position__name='Doctor')
    nurses = User.objects.filter(position__name='Nurse')

    operations = Operation.objects.filter(begin__range=dates)

    operationNames = OperationDictionary.objects.all()

    return render(request, 'operation/allOperationPatient.html', locals())


@login_required
def dateSearchOperation(request):
    """通过日期搜索手术记录"""

    user = User.objects.get(name=request.session['name'])

    # 病房
    wards = user.authorityWard.filter(status=True)

    doctors = User.objects.filter(position__name='Doctor')
    nurses = User.objects.filter(position__name='Nurse')

    operationNames = OperationDictionary.objects.all()

    if request.method == 'POST':
        start = request.POST.get('start')
        end = request.POST.get('end')

        operations = Operation.objects.filter(begin__range=(start, end))

    return render(request, 'operation/allOperationPatient.html', locals())


@login_required
def newPatientBooking(request):
    """添加病人基本信息"""

    # 获取当前需要的数据
    genders = ['', 'ذكر', 'انثى', 'طفل', 'طفلة']
    marriages = ['', 'متزوج', 'اعزب']

    user = User.objects.get(name=request.session['name'])

    # 统计科室的病人
    departments = Department.objects.filter(Q(status=True, types=2) | Q(status=True, types=3))

    message = ''

    if request.method == 'POST':
        name = request.POST.get('name').title()
        age = request.POST.get('age')
        sex = request.POST.get('sex')
        marriage = request.POST.get('marriage')
        address = request.POST.get('address')
        phone = request.POST.get('phone')
        department_id = request.POST.get('department')

        departmentObj = Department.objects.get(id=department_id)

        # 通过年龄计算出生年月日
        tempAge = age
        age = float(age)
        if age <= 1:
            birthday = datetime(datetime.now().year, datetime.now().month, datetime.now().day)

        else:
            age = int(age)
            birthdayYear = datetime.now().year - age
            birthdayMonth = datetime.now().month
            birthdayDay = datetime.now().day
            birthday = datetime(birthdayYear, birthdayMonth, birthdayDay)

        # 判断该病人是否已在数据库
        patient_exist = PatientInfo.objects.filter(basicInfo__name=name, basicInfo__age=age).last()

        if patient_exist:

            message = 'The patient already exists '

            return render(request, 'polyclinic/newPatientPolyclinic.html', locals())

        else:
            numberID = IDCreator()

            basicInfo = BasicInfo.objects.create(name=name, birthday=birthday, sex=sex, age=tempAge,
                                                 marriage=marriage, address=address, phone=phone,
                                                 operator=user.arabic_name)

            patient = PatientInfo.objects.create(basicInfo=basicInfo, patientID=numberID,
                                                 condition=7, operator=user.name)

            # 病人所在的科室
            department_list = [Department.objects.get(id=department_id)]
            patient.department.add(*department_list)

            # 更新该科室的病人数量
            departmentObj.count += 1
            departmentObj.save()

    return render(request, 'operation/newPatientBooking.html', locals())


@login_required
def bookingOperation(request, patient_id):
    """添加手术预定"""

    username = request.session['name']

    if request.method == 'POST':
        name = request.POST.get('name')
        doctor = request.POST.get('doctor')
        begin = request.POST.get('begin')
        # timeOfOperation = request.POST.get('timeOfOperation')
        order = request.POST.get('timeOfOperation')

        # 先检查该日期没有相应的时间表
        if TimeTable.objects.filter(doctor=doctor, date=begin):


templates/operation/bookingList_back.html
{% extends "home/base_operation.html" %}

{% block home %}

    <style>

        td{
            vertical-align: middle;
            text-align: center;
            white-space: nowrap;
        }

        th{
            vertical-align: middle;
            text-align: center;
            white-space: nowrap;

        }

    </style>


    {% if user.language == 1 %}

        <div class="card-header" align="center">

            <h2 class="thirdBigTitle">
                <form action="{% url 'dateSearchBooking' %}" method="post">
                    {% csrf_token %}
                        <label>
                            <input type="date" class="form-control" name="start" required>
                        </label>

                        <label>
                            <input type="submit" class="btn btn-info forthNormalText" value="إرسال">
                        </label>
                </form>
            </h2>

        </div>

        <div class="card-body">

            <div class="table-responsive">

                <table class="table table-bordered">
                    <thead>
                        <tr class="thirdBigTitle">
                            <td style="color: red; font-size: 18px"> ساعة&nbsp;&nbsp;/ {{ dates }}</td>
                            <td>9</td>
                            <td>10</td>
                            <td>11</td>
                            <td>12</td>
                            <td>13</td>
                            <td>14</td>
                            <td>15</td>
                            <td>16</td>
                            <td>17</td>
                            <td>18</td>
                        </tr>
                    </thead>

                    <tbody class="smallText">
                        {% for timeTable in timeTables %}
                            <tr>
                                <td rowspan="2">{{ timeTable.doctor }}</td>
                                {% for booking in timeTable.bookingoperation_set.all %}
                                    <td colspan="{{ booking.timeOfOperation }}" style="color: brown">{{ booking.patient.basicInfo }}</td>
                                {% endfor %}
                            </tr>

                            <tr>

                                {% for booking in timeTable.bookingoperation_set.all %}
                                    <td colspan="{{ booking.timeOfOperation }}" style="color: blueviolet">{{ booking.name }}</td>
                                {% endfor %}
                            </tr>

                        {% endfor %}

                    </tbody>
                </table>

            </div>
        </div>

    {% elif user.language == 2 %}

        <div class="card-header" align="center">

            <h2 class="thirdBigTitle">
                <form action="{% url 'dateSearchBooking' %}" method="post">
                    {% csrf_token %}
                        <label>
                            <input type="date" class="form-control" name="start" required>
                        </label>

                        <label>
                            <input type="submit" class="btn btn-info forthNormalText" value="إرسال">
                        </label>
                </form>
            </h2>

        </div>

        <div class="card-body">

            <div class="table-responsive">

                <table class="table table-bordered">
                    <thead>
                        <tr class="thirdBigTitle">
                            <td style="color: red; font-size: 18px"> ساعة&nbsp;&nbsp;/ {{ dates }}</td>
                            <td>9</td>
                            <td>10</td>
                            <td>11</td>
                            <td>12</td>
                            <td>13</td>
                            <td>14</td>
                            <td>15</td>
                            <td>16</td>
                            <td>17</td>
                            <td>18</td>
                        </tr>
                    </thead>

                    <tbody class="smallText">
                        {% for timeTable in timeTables %}
                            <tr>
                                <td rowspan="2">{{ timeTable.doctor }}</td>
                                {% for booking in timeTable.bookingoperation_set.all %}
                                    <td colspan="{{ booking.timeOfOperation }}" style="color: brown">{{ booking.patient.basicInfo }}</td>
                                {% endfor %}
                            </tr>

                            <tr>

                                {% for booking in timeTable.bookingoperation_set.all %}
                                    <td colspan="{{ booking.timeOfOperation }}" style="color: blueviolet">{{ booking.name }}</td>
                                {% endfor %}
                            </tr>

                        {% endfor %}

                    </tbody>
                </table>

            </div>
        </div>

    {% endif %}





{% endblock home %}







templates/operation/indexBooking.html
{% extends "home/base_booking.html" %}

{% block home %}


    <style type="text/css">

        td{
            vertical-align: middle;
            text-align: center;
            white-space: nowrap;
        }

        th{
            vertical-align: middle;
            text-align: center;
            white-space: nowrap;

        }
    </style>

    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-hover" border="0">
                <tr>
                    <td class="firstBigTitle">
                         ﴾ بِسْمِ اللّٰهِ الرَّحْمٰنِ الرَّح۪يم &nbsp;&nbsp;&nbsp; ﴿ وَإِذَا مَرِضۡتُ فَهُوَ يَشۡفِينِ
                    </td>
                </tr>

            </table>
        </div>
    </div>





{% endblock home %}



templates/operation/indexOperation.html
{% extends "home/base_operation.html" %}

{% block home %}

    <script type="text/javascript" language="JavaScript">
            function excel()
            {
                 alert("Submitted successfully, Please wait !")
            }
     </script>


    <style type="text/css">

        td{
            vertical-align: middle;
            text-align: center;
            white-space: nowrap;
        }

        th{
            vertical-align: middle;
            text-align: center;
            white-space: nowrap;

        }
    </style>

    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-hover" border="0">
                <tr>
                    <td class="firstBigTitle">
                         ﴾ بِسْمِ اللّٰهِ الرَّحْمٰنِ الرَّح۪يم &nbsp;&nbsp;&nbsp; ﴿ وَإِذَا مَرِضۡتُ فَهُوَ يَشۡفِينِ
                    </td>
                </tr>

            </table>
        </div>
    </div>





{% endblock home %}



templates/operation/newPatientBooking.html
{% extends "home/base_booking.html" %}

{% block home %}

    {% if user.language == 1 %}

        <div class="card-header" align="center">
            <h2 class="firstBigTitle">استمارة قبول </h2>
        </div>

        <div class="card-body">
            {% if patient_exist %}
                <h3 style="color: red">{{ message }}<i class="mdi mdi-hand-pointing-right"></i>
                    <a href="/basicInfoPolyclinic/{{ patient_exist.id }}">{{ patient_exist.basicInfo.name }}</a></h3>
            {% endif %}


            <form class="form-horizontal" action="" method="post">
                {% csrf_token %}

                <div class="form-group has-info" style="font-size: 24px; font-family: Calibri">

                    <label class="col-md-2 control-label" for="example-name" style="color: darkblue">اسم المريض</label>
                    <div class="col-md-3">
                      <input class="form-control input-lg" type="text" id="example-name" name="name" autofocus maxlength="30" required dir="rtl">
                    </div>

                    <label class="col-md-2 control-label" for="example-age" style="color: darkblue">العمر</label>
                    <div class="col-md-3">
                      <input class="form-control input-lg" type="number" step="0.1" id="example-age" name="age" required>
                    </div>

                </div>

                <div class="form-group has-info" style="font-size: 24px; font-family: Calibri">

                    <label class="col-md-2 control-label" for="example-sex" style="color: darkblue">الجنس</label>
                    <div class="col-md-3">
                        <select class="form-control input-lg" id="example-select" name="sex" dir="rtl">
                            {% for gender in genders %}
                                <option value="{{gender}}">{{gender}}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <label class="col-md-2 control-label" for="example-select" style="color: darkblue">الحالة العائلية</label>
                    <div class="col-md-3">
                        <select class="form-control input-lg" id="example-select" name="marriage" dir="rtl">
                            {% for marriage in marriages %}
                                <option value="{{ marriage}}">{{marriage}}</option>
                            {% endfor %}
                        </select>
                    </div>

                </div>

                <div class="form-group has-info" style="font-size: 24px; font-family: Calibri">

                    <label class="col-md-2 control-label" for="example-address" style="color: darkblue">السكن</label>
                    <div class="col-md-3">
                      <input class="form-control input-lg" type="text" id="example-address" name="address" required dir="rtl">
                    </div>

                    <label class="col-md-2 control-label" for="example-select" style="color: darkblue">قسم القبول</label>
                    <div class="col-md-3">
                        <select class="form-control input-lg menuSmall" id="example-select" name="department" dir="rtl">
                            <option></option>
                            {% for department in departments %}
                                <option value="{{ department.id }}">{{ department.arabic_name }}</option>
                            {% endfor %}
                        </select>
                    </div>

                </div>

                <br>

                <div class="form-group">
                    <div class="col-md-12 col-md-offset-5">
                        <button class="btn btn-info forthBigMenu" type="submit">إرسال</button>
                    </div>
                </div>


            </form>

        </div>

    {% elif user.language == 2 %}

        <div class="card-header" align="center">
            <h2 class="firstBigTitle">Clinic admission form</h2>
        </div>

        <div class="card-body">
            {% if patient_exist %}
                <h3 style="color: red">{{ message }}<i class="mdi mdi-hand-pointing-right"></i>
                    <a href="/basicInfoPolyclinic/{{ patient_exist.id }}">{{ patient_exist.basicInfo.name }}</a></h3>
            {% endif %}


            <form class="form-horizontal" action="" method="post">
                {% csrf_token %}

                <div class="form-group has-info" style="font-size: 24px; font-family: Calibri">

                    <label class="col-md-2 control-label" for="example-name" style="color: darkblue">Name</label>
                    <div class="col-md-3">
                      <input class="form-control input-lg" type="text" id="example-name" name="name" autofocus maxlength="30" required>
                    </div>

                    <label class="col-md-2 control-label" for="example-age" style="color: darkblue">Age</label>
                    <div class="col-md-3">
                      <input class="form-control input-lg" type="number" step="0.1" id="example-age" name="age" required>
                    </div>

                </div>

                <div class="form-group has-info" style="font-size: 24px">

                    <label class="col-md-2 control-label" for="example-sex" style="color: darkblue">Gender</label>
                    <div class="col-md-3">
                        <select class="form-control input-lg" id="example-select" name="sex">
                            {% for gender in genders %}
                                <option value="{{gender}}">{{gender}}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <label class="col-md-2 control-label" for="example-select" style="color: darkblue">Marriage</label>
                    <div class="col-md-3">
                        <select class="form-control input-lg" id="example-select" name="marriage">
                            {% for marriage in marriages %}
                                <option value="{{ marriage}}">{{marriage}}</option>
                            {% endfor %}
                        </select>
                    </div>

                </div>

                <div class="form-group has-info" style="font-size: 24px">

                    <label class="col-md-2 control-label" for="example-address" style="color: darkblue">Address</label>
                    <div class="col-md-3">
                      <input class="form-control input-lg" type="text" id="example-address" name="address" required>
                    </div>

                    <label class="col-md-2 control-label" for="example-select" style="color: darkblue">Spaciality</label>
                    <div class="col-md-3">
                        <select class="form-control input-lg menuSmall" id="example-select" name="department">
                            <option></option>
                            {% for department in departments %}
                                {% if department.name == 'Internal Cardiology' %}
                                {% else %}
                                    <option value="{{ department.id }}">{{ department.arabic_name }}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    </div>

                </div>

                <br>

                <div class="form-group">
                    <div class="col-md-12 col-md-offset-5">
                        <button class="btn btn-info btn-lg" type="submit">Submit</button>
                    </div>
                </div>


            </form>

        </div>

    {% endif %}





{% endblock home %}
